### ISSUE TITLE
Forum layout

### ISSUE THREAD

**Issue by SnowTHA** [SmaugDev/FGF-site#10]
Actually, the layout of the forum is some blocks and it's not really handsome. Maybe reorganize the layout in bars stacked on top of each other?

Example:
<img width="969" alt="Capture d’écran 2021-03-24 à 20 51 47" src="https://user-images.githubusercontent.com/80066749/112374767-ca550880-8ce2-11eb-8498-fffdafd2d1bb.png">

What do you think ?

**Comment by SmaugDev** [comment]
Yes it's good idea, is planned. On the right is it the latest messages in forum or the last active topics ?

**Comment by SnowTHA** [comment]
The last message in the forum

**Comment by SmaugDev** [comment]
Okay, i will add this and i will remake the style of forum categories

**Comment by SmaugDev** [comment]
On mobile phone, where are the latest messages in forum ? Because the space is insufficient for place them to right.

**Comment by SnowTHA** [comment]
![image](https://user-images.githubusercontent.com/80066749/112446621-afb97880-8d50-11eb-98c3-664bde5263d8.jpeg)

**Comment by SmaugDev** [comment]
A yes i see, thank you

**Comment by SmaugDev** [comment]
I have update this, what do you think ?

**Comment by SmaugDev** [comment]
Forum was removed from website.
