### ISSUE TITLE
Avatars ronds

### ISSUE THREAD

**Issue by SnowTHA** [SmaugDev/FGF-site#11]
Make the avatars round and framed in black / white for everyone?

**Ex:**
<img width="153" alt="Capture d’écran 2021-04-02 à 10 59 19" src="https://user-images.githubusercontent.com/80066749/113400788-abb9d600-93a2-11eb-8afc-d50898a82b76.png">

**Comment by SmaugDev** [comment]
A yes in the forum they are not yet round. But in the navbar they already are. I'll change that.

**Comment by SnowTHA** [comment]
Ok

**Comment by SmaugDev** [comment]
Solved
