### ISSUE TITLE
Style de la messagerie

### ISSUE THREAD

**Issue by SnowTHA** [SmaugDev/FGF-site#12]
I suggest for messaging to grow the edges of the page a bit. I also suggest putting the messages framed with the rounded edges and colored a bit transparent white instead of square black?

<img width="858" alt="Capture d’écran 2021-04-02 à 10 59 30" src="https://user-images.githubusercontent.com/80066749/113401080-1ff47980-93a3-11eb-9aee-2d84908c8149.png">

**Comment by SmaugDev** [comment]
A yes and i have see  that on mobile there is a problem with the color of messages

**Comment by SnowTHA** [comment]
Yes, personally there is just a white cube ^^

**Comment by SmaugDev** [comment]
I have update style of messages, what do you think ?
