### ISSUE TITLE
Add template

### ISSUE THREAD

**Issue by SmaugDev** [SmaugDev/FGF-site#6]
Ajouter une option de templates pour les articles notament pour les tests de jeux vidéos. Cette option pourrait ce trouver dans l'editeur markdown

**Comment by SnowTHA** [comment]
Empêcher les débordements des images.
http://161.97.66.77:8081/articles/view/14

Ajouter la possibilité de poster des codes HTML ? (Pour des sujets plus esthétiques ?)

**Comment by SmaugDev** [comment]
The users can already add html in articles

**Comment by SnowTHA** [comment]
Ok ✅
