### ISSUE TITLE
Group colors

### ISSUE THREAD

**Issue by SnowTHA** [SmaugDev/FGF-site#7]
Add color on group like red for administration, green for moderation etc..

Review the group administration board ?
This > https://i.goopics.net/ed13D.png
Maybe something like this ? > https://i.goopics.net/nxD0w.png

Add also group tag (or just name and color) under pseudo on profil page (because we don't know who's who) ...
> https://i.goopics.net/Gda3K.png

**Comment by SmaugDev** [comment]
Yes, i will remake the badge system on all site for view badges of members on account page, articles etc. 
And effectively i will add specific color for badges.

**Comment by SmaugDev** [comment]
For the badges system, i have five badges (Admin, Modo, Rédacteur, Partenaire, Testeur). You think we need more ?

**Comment by SmaugDev** [comment]
Solved with permissions. in future i will add others roles/permissions
