### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by SnowTHA** [SmaugDev/FGF-site#8]
Remove the pictures of the main page (pictures from articles) and replace with the new one.

Old pictures > https://i.goopics.net/Gda3v.png
New pictures >
![1](https://user-images.githubusercontent.com/80066749/112053460-ab287080-8b54-11eb-8e81-9fbb2fa3c29b.jpg)
![2](https://user-images.githubusercontent.com/80066749/112053472-aebbf780-8b54-11eb-8bfd-a7c45c6b69fd.jpg)
![3](https://user-images.githubusercontent.com/80066749/112053476-afed2480-8b54-11eb-87ec-f19ef182f565.jpg)
![4](https://user-images.githubusercontent.com/80066749/112053482-b1b6e800-8b54-11eb-819e-02cb17fb416d.jpg)
![5](https://user-images.githubusercontent.com/80066749/112053486-b2e81500-8b54-11eb-9629-0d9827cec4d5.png)

**Comment by SmaugDev** [comment]
I have this result, it's clean 💪 
![image](https://user-images.githubusercontent.com/59796136/112055092-b67c9b80-8b56-11eb-8257-97fdee4a630a.png)

**Comment by SnowTHA** [comment]
Nice, could you add a timer which 
automatically scroll pictures ?

**Comment by SmaugDev** [comment]
A yes good idea

**Comment by SmaugDev** [comment]
I have deployed the changes, what do you think ?

**Comment by SnowTHA** [comment]
It's look good, I like it, good job.

I close this issue ✅
