### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by SmaugDev** [SmaugDev/FGF-site#9]
I have succeeded created member permissions system, but i don't know what permissions do we need. For the moment i have created :
VIEW_MEMBERS
VIEW_ADMIN_DASHBOARD
UPDATE_MEMBER
DELETE_MEMBER
BAN_MEMBERS
MANAGE_REQUESTS
MANAGE_ALBUM
MANAGE_ARTICLES
MANAGE_ANNOUNCEMENTS

What do you think about this list of permissions @SnowTHA ?

**Comment by SmaugDev** [comment]
After having think, i think the good permissions for FGF site are : ADMINISTRATOR
MODERATOR
VIEW_ADMIN_DASHBOARD
MANAGE_MEMBERS
MANAGE_ARTICLES
MANAGE_FORUM
MANEGE_REQUESTS
MANAGE_ANNOUNCEMENTS

If you think i have missing permissions in this list say it to me

**Comment by SnowTHA** [comment]
Yes, maybe MANAGE_SUBJECTPREFIX ? (To manage prefix on thread ?) 

It's good ✅

**Comment by SmaugDev** [comment]
What is prefix ?

**Comment by SnowTHA** [comment]
Prefix is tags before thread ? Like "Accepté" "Refusé" "En attente" "Informations" "Important" ? You know what I mean ?

I will add an example:
<img width="553" alt="Capture d’écran 2021-03-24 à 20 41 46" src="https://user-images.githubusercontent.com/80066749/112373572-667e1000-8ce1-11eb-92eb-b799e64d5520.png">

**Comment by SmaugDev** [comment]
A yes okay, the prefix are update when the request is accepted ou refused. So for requests for exemple, the permission is MANAGE_REQUESTS, for articles the permission is MANAGE_ARTICLES etc.

**Comment by SnowTHA** [comment]
We can't add other prefix ?

**Comment by SmaugDev** [comment]
Currently the prefix is "en attente" "validé" "refusé" for requests, photos, article. What other prefix we need ?

**Comment by SnowTHA** [comment]
At this moment nothing I think

**Comment by SmaugDev** [comment]
Solved
